config/routes.rb
Rails.application.routes.draw do

  # アーティスト会員用
  namespace :artist do
    resources :public_users, only:[:show] do
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
    end
    resources :artist_users, only:[:index] do
      collection do
        get 'my_page' => 'artist_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'my_page/my_topics' => 'artist_users#my_topics'
        get 'information/edit' => 'artist_users#edit'
        patch 'information' => 'artist_users#update'
        get 'unsubscribe' => 'artist_users#unsubscribe'
        patch 'hide' => 'artist_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
        get 'search' => 'artist_users#search'
      end

      member do
        get 'profile' => 'profiles#show'
        get 'profile/edit' => 'profiles#edit'
        patch 'profile' => 'profiles#update', as: 'profile_update'
      end
      resources :live_schedules, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :items, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :profile_topics, only:[:index]
      resources :rooms, only:[:index]
      # resource :relationships, only:[:create, :destroy]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
    end

    resources :genres, only:[:index, :create]
    resources :topics do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
        delete 'topic/:id' => 'topics#from_index_destroy', as: 'from_index_destroy'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
  end

  namespace :public do
    resources :public_users, only:[] do
      collection do
        get 'my_page' => 'public_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'information/edit' => 'public_users#edit'
        patch 'information' => 'public_users#update'
        get 'unsubscribe' => 'public_users#unsubscribe'
        patch 'hide' => 'public_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
      end
      get 'profile' => 'public_users#public_profile'
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
      resources :rooms, only:[:index]
    end
    resources :artist_users, only:[:index] do
      member do
        get 'profile' => 'profiles#show'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
      resources :live_schedules, only:[:index]
      resources :items, only:[:index]
      resources :profile_topics, only:[:index]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
    end
    resources :topics, only:[:index, :show] do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 管理者用
  namespace :admin do
    get '/' => 'homes#top'
    resources :public_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'public_users#guest_delete'
      end
      collection do
        get 'search' => 'public_users#search'
      end
    end
    resources :artist_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'artist_users#guest_delete'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
    end
    resources :genres, only:[:index, :edit, :create, :update, :destroy]
    resources :topics, only:[:index, :show, :destroy] do
      resources :topic_comments, only:[:destroy]
      collection do
        resources :tags, only:[:index, :destroy]
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員ゲストログイン用
  devise_scope :public_user do
    post 'public_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # Artist会員ゲストログイン用
  devise_scope :artist_user do
    post 'artist_users/guest_sign_in', to: 'artist/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # アーティスト会員用
  devise_for :artist_users,skip: [:passwords], controllers: {
    registrations: "artist/registrations",
    sessions: "artist/sessions"
  }

  # 一般会員用
  devise_for :public_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/artist_user.rb
class ArtistUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :genre, optional: true
  has_many :live_schedules, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :topic_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :joins, dependent: :destroy

  # followをした、followをされたの関係
  has_many :artist_relationships, class_name: "Relationship", foreign_key: "artist_follower_id", dependent: :destroy
  has_many :artist_reverse_of_relationships, class_name: "Relationship", foreign_key: "artist_followed_id", dependent: :destroy

  # followをしているかの確認時に
  has_many :artist_followings, through: :artist_relationships, source: :artist_followed
  has_many :public_followings, through: :artist_relationships, source: :public_followed

  has_one_attached :profile_image
  has_one_attached :header_image

  validates :artist_name, presence: true
  validates :rep_name, presence: true
  validates :rep_name_kana, presence: true
  validates :activity_location, presence: true

  # 退会していないユーザーを取得するための記述
  scope :active, -> { where(is_deleted: false) }

  # 退会しているユーザーを取得するための記述
  scope :deleted, -> { where(is_deleted: true) }

  # Artistの検索機能（絞り込み検索）
  scope :search, -> (search_params) do
    return if search_params.blank?

    # パラメータを指定して検索を実行する
    artist_name_like(search_params[:artist_name])
      .genre_id_is(search_params[:genre_id])
      .activity_location_is(search_params[:activity_location])
  end

  # artist_nameが存在する場合、artist_nameをlike検索する
  scope :artist_name_like, -> (artist_name) { where('artist_name LIKE ?', "%#{artist_name}") if artist_name.present? }
  # genre_idが存在する場合、genre_idで検索する
  scope :genre_id_is, -> (genre_id) { where(genre_id: genre_id) if genre_id.present? }
  # activity_locationが存在する場合、activity_locationで検索する
  scope :activity_location_is, -> (activity_location) { where(activity_location: activity_location) if activity_location.present? }

  # ゲストログイン機能のメソッド
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |artist_user|
      artist_user.password = SecureRandom.urlsafe_base64
      artist_user.rep_name = "ゲスト"
      artist_user.rep_name_kana = "ゲスト"
      artist_user.artist_name = "ゲストユーザー"
      artist_user.activity_location = 0
    end
  end

  # フォロー中の退会していないユーザーを取得するメソッド
  def active_followings
    active_box = []
    # フォロー中のArtist会員のRelationshipsのidを取り出し、active_boxに格納
    self.artist_relationships.active_artist_followed.each do |following|
      active_box << following.id
    end
    # フォロー中の一般会員のRelationshipsのidを取り出し、active_boxに格納
    self.artist_relationships.active_public_followed.each do |following|
      active_box << following.id
    end
     # 上記で取得したRelationshipsのid（active_box）を使用し、退会していないユーザー（Artist会員、一般会員の両方）を取得する。
    Relationship.where(id: active_box)
  end

   # フォロワーの退会していないユーザーを取得するメソッド
  def active_followers
    active_box = []
    # フォロワーののArtist会員のRelationshipsのidを取り出し、active_boxに格納
    self.artist_reverse_of_relationships.active_artist_follower.each do |follower|
      active_box << follower.id
    end
    # フォロワーの一般会員のRelationshipsのidを取り出し、active_boxに格納
    self.artist_reverse_of_relationships.active_public_follower.each do |follower|
      active_box << follower.id
    end
    # 上記で取得したRelationshipsのid（active_box）を使用し、退会していないユーザー（Artist会員、一般会員の両方）を取得する。
    Relationship.where(id: active_box)
  end

  # followをしたときの処理
  def follow_an_artist(artist_user_id)
    artist_relationships.create(artist_followed_id: artist_user_id)
  end

  def follow_an_public(public_user_id)
    artist_relationships.create(public_followed_id: public_user_id)
  end

  # followを外すときの処理
  def unfollow_an_artist(artist_user_id)
    artist_relationships.find_by(artist_followed_id: artist_user_id).destroy
  end

  def unfollow_an_public(public_user_id)
    artist_relationships.find_by(public_followed_id: public_user_id).destroy
  end

  # followをしているか判定をする処理
  def artist_following?(artist_user)
    artist_followings.include?(artist_user)
  end

  def public_following?(public_user)
    public_followings.include?(public_user)
  end

  # プロフィール画像取得するメソッド
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/profile_no_image.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  # ヘッダー画像を取得するメソッド
  def get_header_image
    unless header_image.attached?
      file_path = Rails.root.join('app/assets/images/profile_no_header_image.jpg')
      header_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    header_image
  end

  enum activity_location: {
    hokkaido: 0, aomori: 1, iwate: 2, miyagi: 3, akita: 4, yamagata: 5, fukushima: 6, ibaraki: 7, tochigi: 8, gunma: 9, saitama: 10,
    chiba: 11, tokyo: 12, kanagawa: 13, niigata: 14, toyama: 15, ishikawa: 16, fukui: 17, yamanashi: 18, nagano: 19, gifu: 20,
    shizuoka: 21, aichi: 22, mie: 23, shiga: 24, kyoto: 25, osaka: 26, hyogo: 27, nara: 28, wakayama: 29, tottori: 30,
    shimane: 31, okayama: 32, hiroshima: 33, yamaguchi: 34, tokushima: 35, kagawa: 36, ehime: 37, kochi: 38, fukuoka: 39, saga: 40,
    nagasaki: 41, kumamoto: 42, oita: 43, miyazaki: 44, kagoshima: 45, okinawa: 46
  }

end

app/controllers/admin/artist_users_controller.rb
class Admin::ArtistUsersController < ApplicationController
  before_action :authenticate_admin!
  # ArtistUser一覧
  def index
    # ジャンルを指定してindexページを表示させる
    if params[:genre_id].present?
      @genre = Genre.find(params[:genre_id])
      @artist_users = @genre.artist_users.page(params[:page]).per(10)
      @search_params = artist_user_search_params

    # ジャンル設定をしていないArtistUserを指定しindexページを表示させる
    elsif params[:genre_nil].present?
      @artist_users = ArtistUser.where(genre_id: nil).all.page(params[:page]).per(10)
      @search_display = "未設定"
      @search_params = artist_user_search_params

    # 退会しているArtistUserを指定し、indexページを表示させる
    elsif params[:no_active].present?
      @artist_users = ArtistUser.deleted.page(params[:page]).per(10)
      @search_display = "退会済みのアカウント"
      @search_params = artist_user_search_params

    # ジャンルは指定せず、indexページを表示させる(全てのArtistUser)
    else
      @artist_users = ArtistUser.all.page(params[:page]).per(10)
      @search_params = artist_user_search_params
    end
  end

  # ArtistUser検索アクション
  def search
    @search_params = artist_user_search_params
    @artist_users = ArtistUser.search(@search_params).includes(:genre).page(params[:page]).per(10)
    render "index"
  end

  # ArtistUser詳細画面
  def show
    @artist_user = ArtistUser.find(params[:id])
  end

  # ArtistUser情報編集
  def edit
    @artist_user = ArtistUser.find(params[:id])
  end

  # ArtistUser情報更新
  def update
    @artist_user = ArtistUser.find(params[:id])
    @artist_user.update(artist_user_params)
    redirect_to admin_artist_user_path
  end

  # ゲストユーザーを削除
  def guest_delete
    artist_user = ArtistUser.find(params[:id])
    artist_user.destroy
    redirect_to admin_artist_users_path
  end

  private
  # ストロングパラメータ
  def artist_user_params
    params.require(:artist_user).permit(:artist_name, :rep_name, :rep_name_kana, :genre_id, :activity_location, :email, :youtube_url, :is_deleted)
  end

  def artist_user_search_params
    params.fetch(:search, {}).permit(:artist_name, :genre_id, :activity_location)
  end
end

app/controllers/artist/artist_users_controller.rb
class Artist::ArtistUsersController < ApplicationController
  before_action :authenticate_artist_user!
  # Artist一覧画面
  def index
    @genres = Genre.all
    @artist_user = current_artist_user
    @search_params = artist_user_search_params

    # サイドバーのジャンル検索ボタンを押された時の処理
    if params[:name].present?
      # 指定されたジャンルに紐づいている、退会していないArtistUserを取得
      @artist_users = Genre.find(params[:name]).artist_users.active.order(created_at: :desc).page(params[:page]).per(9)
    else
      # 退会していないArtistUserを取得
      @artist_users = ArtistUser.active.order(created_at: :desc).page(params[:page]).per(9)
    end
  end

  # Artist検索アクション
  def search
    @artist_user = current_artist_user
    @genres = Genre.all
    @search_params = artist_user_search_params
    # 最新順でArtistUserを表示させる場合
    if params[:display_select] == "1"
      @artist_users = ArtistUser.active.search(@search_params).includes(:genre).order(created_at: :desc).page(params[:page]).per(9)
    # 登録日順でArtistUserを表示させる場合
    elsif params[:display_select] == "2"
      @artist_users = ArtistUser.active.search(@search_params).includes(:genre).page(params[:page]).per(9)
    # フォロワーが多い順でArtistUserを表示させる場合
    elsif params[:display_select] == "3"
      @artist_users = Kaminari.paginate_array(ArtistUser.active.search(@search_params).includes(:genre).sort {|a, b| b.active_followers.count.to_i <=> a.active_followers.count.to_i}).page(params[:page]).per(9)
    # フォロワーが少ない順でArtistUserを表示させる場合
    elsif params[:display_select] == "4"
      @artist_users = Kaminari.paginate_array(ArtistUser.active.search(@search_params).includes(:genre).sort {|a, b| a.active_followers.count.to_i <=> b.active_followers.count.to_i}).page(params[:page]).per(9)
    end
    render "index"
  end

  # My page
  def show
    @artist_user = current_artist_user
    # TimeLineを表示するため、自身のtopicsとfollowしている退会していないユーザーのtopicsを取得
    @topics = Topic.active_topics.where(artist_user_id: [current_artist_user.id, *current_artist_user.artist_following_ids]).order(created_at: :desc).page(params[:page]).per(10)
  end

  # My pageで自身が投稿したtopic一覧を表示するためのアクション
  def my_topics
    @artist_user = current_artist_user
    @topics = @artist_user.topics.order(created_at: :desc).page(params[:page]).per(10)
  end

  # 登録情報編集画面
  def edit
    @artist_user = current_artist_user
  end

  # 登録情報更新
  def update
    @artist_user = current_artist_user
    # ログイン中のユーザーがゲストユーザーの場合はアーティスト名、メールアドレス以外を編集可能にする。
    if @artist_user.email == 'guest@example.com'
      flash[:notice] = "ゲストユーザーのため、アーティスト名、メールアドレス以外を更新しました。"
      @artist_user.update(params.require(:artist_user).permit(:profile_image, :rep_name, :rep_name_kana, :activity_location, :genre_id))
      redirect_to my_page_artist_artist_users_path
    else
      flash[:notice] = "登録情報を更新しました。"
      @artist_user.update(artist_user_params)
      redirect_to my_page_artist_artist_users_path
    end
  end

  # 退会確認画面
  def unsubscribe
    @artist_user = current_artist_user
  end

  # 退会処理(論理削除)
  def hide
    @artist_user = current_artist_user
    @artist_user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private
  # ストロングパラメータ
  def artist_user_params
    params.require(:artist_user).permit(:profile_image, :artist_name, :rep_name, :rep_name_kana, :activity_location, :email, :genre_id)
  end

  def artist_user_search_params
    params.fetch(:search, {}).permit(:artist_name, :genre_id, :activity_location)
  end
end

app/helpers/admin/artist_users_helper.rb
module Admin::ArtistUsersHelper
end

app/helpers/artist/artist_users_helper.rb
module Artist::ArtistUsersHelper
end

app/views/admin/artist_users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto mt-4">
      <h4 class="text-white">Artist会員 一覧</h4>
    </div>

    <!--Artist会員絞り込み検索フォームの設置-->
    <div class="search-form p-3 mx-auto col-md-10">
      <%= form_with(scope: :search, url: search_admin_artist_users_path, method: :get, local: true) do |f| %>
        <div class="field">
          <%= f.label :artist_name, "アーティスト名", class: "text-white col-2" %>
          <%= f.text_field :artist_name, value: @search_params[:artist_name], placeholder: 'Search' %>
        </div>
        <div class="field">
          <%= f.label :genre_id, "ジャンル選択", class: "text-white col-2" %>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, selected: @search_params[:genre_id], include_blank: t('helpers.select.全て')) %>
        </div>
        <div class="field">
          <%= f.label :activity_location, "エリアを選択", class: "text-white col-2" %>
          <%= f.select :activity_location, ArtistUser.activity_locations_i18n.invert, selected: @search_params[:activity_location], include_blank: t('helpers.select.全て') %>
          <div class="text-center">
            <%= f.submit "検索", class: "btn btn-success btn-green col-5" %>
          </div>
        </div>
      <% end %>
    </div>

    <!--ジャンルを指定した場合のテキスト表示-->
    <% if params[:genre_id].present? %>
      <div class="col-md-10 mx-auto mt-4">
        <p class="text-info">ジャンル "<%= @genre.name %>" を設定しているArtist会員</p>
      </div>

    <!--ジャンル設定が未設定のArtistUserを指定し、表示させる場合のテキスト表示-->
    <% elsif params[:genre_nil].present? %>
      <div class="col-md-10 mx-auto mt-4">
        <p class="text-info">ジャンル登録が " <%= @search_display %> " のArtist会員</p>
      </div>

    <!--退会済みのArtistUserを指定し、表示させる場合のテキスト表示-->
    <% elsif params[:no_active].present? %>
      <div class="col-md-10 mx-auto mt-4">
        <p class="text-info"><%= @search_display %></p>
      </div>
    <% end %>
    <div class="col-md-10 mt-3 mx-auto">
      <!--Artist会員の一覧をテーブルで表示-->
      <table class="table table-hover table-borderless text-white">
        <thead class="border-bottom">
          <tr>
            <th>会員ID</th>
            <th>アーティスト名</th>
            <th>代表者氏名</th>
            <th>ジャンル</th>
            <th>メールアドレス</th>
            <th class="text-right">Topics</th>
            <th class="text-center">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @artist_users.each do |artist_user| %>
          <tr>
            <td>
              <span class="text-white"><%= artist_user.id %></span>
            </td>
            <td>
              <%= link_to artist_user.artist_name, admin_artist_user_path(artist_user.id), class: "text-white border-bottom" %>
            </td>
            <td>
              <span class="text-white"><%= artist_user.rep_name %></span>
            </td>
            <td>
              <!--取得したArtistUserがジャンルを登録していた場合の表示-->
              <% if artist_user.genre.present? %>
                <!--取得したジャンルでArtistUserを検索できるようリンクを設置-->
                <%= form_tag admin_artist_users_path do %>
                  <%= link_to admin_artist_users_path(genre_id: artist_user.genre.id), class: "border-bottom" do %>
                    <span class="text-white"><%= artist_user.genre.name %></span>
                  <% end %>
                <% end %>

              <!--取得したArtistUserがジャンル登録をしていない場合の表示-->
              <% else %>
                <!--ジャンル設定が未設定(genre_id = nil)のArtistUserを検索できるようリンクを設置-->
                <%= form_tag admin_artist_users_path do %>
                  <%= link_to admin_artist_users_path(genre_nil: 0), class: "border-bottom" do %>
                    <span class="text-white-50">未設定</span>
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <td>
              <span class="text-white"><%= artist_user.email %></span>
            </td>
            <!-- Topicsの投稿数を表示させ、クリックでアーティストを指定したTopics一覧を表示できるようリンクを設置-->
            <%= form_tag admin_topics_path, method: :get do %>
              <td class="text-right"><%= link_to artist_user.topics.count, admin_topics_path(artist_id: artist_user.id), class: "text-white border-bottom" %></td>
            <% end %>
            <td class="text-center">
              <% if artist_user.is_deleted == false %>
              <span class="text-success"><strong>有効</strong></span>
              <% else %>
              <span class="text-danger"><strong>退会</strong></span>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!--ページネーションの表示-->
    <div class="col-md-12 d-flex justify-content-center mt-5">
      <div>
        <%= paginate @artist_users %>
      </div>
    </div>

  </div>
</div>

app/views/admin/artist_users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto mt-4 d-flex align-items-center">
      <!--Artist会員のプロフィールイメージと、アーティスト名を表示-->
      <%= image_tag @artist_user.get_profile_image, class: "dedail-page-profile-image" %>
      <span class="text-white h4 ml-3"><%= @artist_user.artist_name %>さんの会員詳細</span>
    </div>

    <div class="col-md-10 mt-3 mx-auto box p-4">
      <div class="row text-white">
        <!--会員のIDを表示-->
        <div class="col-md-3">
          <p>会員ID</p>
        </div>
        <div class="col-md-9">
          <%= @artist_user.id %>
        </div>

        <!--アーティスト名の表示-->
        <div class="col-md-3">
          <p>アーティスト名</p>
        </div>
        <div class="col-md-9">
          <%= @artist_user.artist_name %>
        </div>

        <!--代表者氏名の表示-->
        <div class="col-md-3">
          <p>代表者氏名</p>
        </div>
        <div class="col-md-9">
          <%= @artist_user.rep_name %>
        </div>

        <!--代表者氏名フリガナの表示-->
        <div class="col-md-3">
          <p>代表者氏名フリガナ</p>
        </div>
        <div class="col-md-9">
          <%= @artist_user.rep_name_kana %>
        </div>

        <!--登録ジャンルの表示-->
        <div class="col-md-3">
          <p>ジャンル名</p>
        </div>
        <div class="col-md-9">
          <% if @artist_user.genre.present? %>
            <%= @artist_user.genre.name %>
          <% else %>
            <span class="text-white-50">未設定</span>
          <% end %>
        </div>

        <!--出身地の表示-->
        <div class="col-md-3">
          <p>出身</p>
        </div>
        <div class="col-md-9">
          <%= @artist_user.activity_location_i18n %>
        </div>

        <!--メールアドレスの表示-->
        <div class="col-md-3">
          <p>メールアドレス</p>
        </div>
        <div class="col-md-9">
          <%= @artist_user.email %>
        </div>

        <!--プロフィールに登録しているyoutubeのURLの表示-->
        <div class="col-md-3">
          <p>Youtube URL</p>
        </div>
        <div class="col-md-9">
          <%= @artist_user.youtube_url %>
        </div>

        <!--トピックスの投稿数を表示させ、トピックス一覧画面へ遷移するリンクを設置-->
        <div class="col-md-3">
          <p>Topics 投稿数</p>
        </div>
        <div class="col-md-9">
          <%= form_tag admin_topics_path do %>
            <%= link_to admin_topics_path(artist_id: @artist_user.id), class: "text-white border-bottom" do %>
              <%= @artist_user.topics.count %>
            <% end %>
          <% end %>
        </div>

        <!--会員ステータスの表示-->
        <div class="col-md-3">
          <p>会員ステータス</p>
        </div>
        <div class="col-md-9">
          <% if @artist_user.is_deleted == false %>
          <!--退会していなければ"有効"と表示-->
          <span class="text-success"><strong>有効</strong></span>
          <% else %>
          <!--退会していれば"退会"と表示-->
          <span class="text-danger"><strong>退会</strong></span>
          <% end %>
        </div>
        <div class="col-md-3 col-form-label">
        </div>

        <!--会員情報編集ページへのボタンを設置-->
        <div class="col-md-9 col-form-label">
          <%= link_to "編集する", edit_admin_artist_user_path(@artist_user.id), class: "btn btn-success btn-follow col-md-3" %>
          <!--ゲストユーザーの場合のみ削除ボタンを表示させる。-->
          <% if @artist_user.email == 'guest@example.com' %>
            <%= link_to "ゲストユーザーを削除",delete_admin_artist_user_path(@artist_user.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger btn-red col-md-3 mx-5" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>