config/routes.rb
Rails.application.routes.draw do

  # アーティスト会員用
  namespace :artist do
    resources :public_users, only:[:show] do
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
    end
    resources :artist_users, only:[:index] do
      collection do
        get 'my_page' => 'artist_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'my_page/my_topics' => 'artist_users#my_topics'
        get 'information/edit' => 'artist_users#edit'
        patch 'information' => 'artist_users#update'
        get 'unsubscribe' => 'artist_users#unsubscribe'
        patch 'hide' => 'artist_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
        get 'search' => 'artist_users#search'
      end

      member do
        get 'profile' => 'profiles#show'
        get 'profile/edit' => 'profiles#edit'
        patch 'profile' => 'profiles#update', as: 'profile_update'
      end
      resources :live_schedules, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :items, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :profile_topics, only:[:index]
      resources :rooms, only:[:index]
      # resource :relationships, only:[:create, :destroy]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
    end

    resources :genres, only:[:index, :create]
    resources :topics do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
        delete 'topic/:id' => 'topics#from_index_destroy', as: 'from_index_destroy'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
  end

  namespace :public do
    resources :public_users, only:[] do
      collection do
        get 'my_page' => 'public_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'information/edit' => 'public_users#edit'
        patch 'information' => 'public_users#update'
        get 'unsubscribe' => 'public_users#unsubscribe'
        patch 'hide' => 'public_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
      end
      get 'profile' => 'public_users#public_profile'
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
      resources :rooms, only:[:index]
    end
    resources :artist_users, only:[:index] do
      member do
        get 'profile' => 'profiles#show'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
      resources :live_schedules, only:[:index]
      resources :items, only:[:index]
      resources :profile_topics, only:[:index]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
    end
    resources :topics, only:[:index, :show] do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 管理者用
  namespace :admin do
    get '/' => 'homes#top'
    resources :public_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'public_users#guest_delete'
      end
      collection do
        get 'search' => 'public_users#search'
      end
    end
    resources :artist_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'artist_users#guest_delete'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
    end
    resources :genres, only:[:index, :edit, :create, :update, :destroy]
    resources :topics, only:[:index, :show, :destroy] do
      resources :topic_comments, only:[:destroy]
      collection do
        resources :tags, only:[:index, :destroy]
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員ゲストログイン用
  devise_scope :public_user do
    post 'public_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # Artist会員ゲストログイン用
  devise_scope :artist_user do
    post 'artist_users/guest_sign_in', to: 'artist/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # アーティスト会員用
  devise_for :artist_users,skip: [:passwords], controllers: {
    registrations: "artist/registrations",
    sessions: "artist/sessions"
  }

  # 一般会員用
  devise_for :public_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :artist_user
  has_many :topic_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :topic_tags, dependent: :destroy

  # throughオプションによりtopic_tagsテーブルを通してtagsテーブルとの関連付け
  has_many :tags, through: :topic_tags

  has_one_attached :topic_image

  validates :body, presence: true

  # 退会していないユーザーだけのトピックスを表示させるための記述
  scope :active_topics, -> { where(artist_user_id: ArtistUser.active) }
  # 退会しているユーザーだけのトピックスを表示させるための記述
  scope :not_active_topics, -> { where(artist_user_id: ArtistUser.deleted) }

  def save_tag(sent_tags)
    # タグが存在していれば、タグ名を配列としてすべて取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    # 現在取得したタグから送られてきたタグを除いてold_tagとする
    old_tags = current_tags - sent_tags

    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_tag|
      self.tags.delete Tag.find_by(name: old_tag)
    end

    # 新しいタグを保存する
    new_tags.each do |new_tag|
      new_topic_tag = Tag.find_or_create_by(name: new_tag)
      self.tags << new_topic_tag
    end
  end

  # トピックスのキーワード検索
  def self.search(keyword)
    Topic.where(["body LIKE?", "%#{keyword}"])
  end

  # いいねをしているかを判断するメソッド
  def public_user_favorited_by?(public_user)
    favorites.exists?(public_user_id: public_user.id)
  end

  # いいねをしているかを判断するメソッド
  def artist_user_favorited_by?(artist_user)
    favorites.exists?(artist_user_id: artist_user.id)
  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  before_action :authenticate_admin!
  # Topics一覧
  def index
    # Artistを指定してトピックス一覧ページを表示させる場合
    if params[:artist_id].present?
      @artist_user = ArtistUser.find(params[:artist_id])
      @topics = ArtistUser.find(params[:artist_id]).topics.order(created_at: :desc).page(params[:page]).per(10)
      @tag_lists = Tag.all

    # Artistは指定せず、トピックス一覧ページを表示させる場合
    else
      @topics = Topic.all.order(created_at: :desc).page(params[:page]).per(10)
      @tag_lists = Tag.all
    end
  end

  # トピックス詳細画面を表示
  def show
    @topic = Topic.find(params[:id])
    @topic_comments = @topic.topic_comments.order(created_at: :desc).page(params[:page]).per(6)
  end

  # トピックスを削除するアクション
  def destroy
    topic = Topic.find(params[:id])
    topic.destroy
    redirect_to admin_topics_path
  end

  # キーワード検索アクション
  def search
    @tag_lists = Tag.all
    @topics = Topic.search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(10)
    @keyword = params[:keyword]
    render "index"
  end

  # タグ検索アクション
  def tag_search
    @tag_lists = Tag.all
    @tag = Tag.find(params[:tag_id])
    @topics = @tag.topics.all.order(created_at: :desc).page(params[:page]).per(10)
    @search_display = @tag.name
    render "index"
  end
end

app/controllers/artist/topics_controller.rb
class Artist::TopicsController < ApplicationController
  before_action :authenticate_artist_user!
  # トピックス新規投稿画面
  def new
    @topic =Topic.new
  end

  # トピックス新規作成アクション
  def create
    @topic = current_artist_user.topics.new(topic_params)

    # 受け取ったタグの値をスペースで区切り配列にし保存する(半角と全角の両方を対応させる)
    @tag_list = params[:topic][:name].split(/[ |　]/)
    if @topic.save
      @topic.save_tag(@tag_list)
      redirect_to artist_topic_path(@topic)
    else
      render :new
    end
  end

  # トピックス一覧画面
  def index
    @artist_user = current_artist_user
    # 退会していないユーザーのトピックスを取得
    @topics = Topic.active_topics.order(created_at: :desc).page(params[:page]).per(10)
    # 退会していないユーザーのトピックスに紐づくすべてのタグを取得
    @tag_lists = Tag.active_tags
  end

  # トピックス詳細画面
  def show
    @topic = Topic.find(params[:id])
    # トピックスに紐づいているコメントを取得（退会していないユーザーのみ）
    @topic_comments = @topic.topic_comments.active_comments.order(created_at: :desc).page(params[:page]).per(6)
    @topic_comment = TopicComment.new
    # コメント数
    @topic_comments_count = @topic_comments.total_count
  end

  # トピックス編集画面
  def edit
    @topic = Topic.find(params[:id])
    @tag_list = @topic.tags.pluck(:name).join('　')
    # 他人の投稿したトピックスの編集画面に遷移させない
    if @topic.artist_user_id != current_artist_user.id
      redirect_to artist_topics_path
    end
  end

  # トピックス情報更新
  def update
    topic = Topic.find(params[:id])
    tag_list = params[:topic][:name].split(/[ |　]/)

    if topic.update(topic_params)
      topic.save_tag(tag_list)
      redirect_to artist_topic_path(topic)
    else
      @topic = Topic.find(params[:id])
      render :edit
    end
  end

  # トピックス情報削除(詳細画面からの削除ボタンクリック時)
  def destroy
    topic = Topic.find(params[:id])
    topic.destroy
    redirect_to artist_topics_path
  end

  # トピックス情報削除(トピックス一覧画面からの削除ボタンクリック時)
  def from_index_destroy
    topic = Topic.find(params[:id])
    topic.destroy
    redirect_to request.referer
  end

  # トピックス検索アクション
  def search
    @artist_user = current_artist_user
    @tag_lists = Tag.active_tags
    @topics = Topic.active_topics.search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(10)
    @keyword = params[:keyword]
    render "index"
  end

  # タグ検索アクション
  def tag_search
    @artist_user = current_artist_user
    @tag_lists = Tag.active_tags
    @tag = Tag.find(params[:tag_id])
    @topics = @tag.topics.active_topics.order(created_at: :desc).page(params[:page]).per(10)
    @search_display = @tag.name
    render "index"
  end

  private
  # ストロングパラメータ
  def topic_params
    params.require(:topic).permit(:artist_user_id, :body, :topic_image, :youtube_url)
  end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/artist/topics_helper.rb
module Artist::TopicsHelper
end

app/views/admin/topics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto mt-4">
      <% if params[:artist_id].present? %>
      <!--アーティストを指定し、Topics一覧を表示させる場合-->
        <div>
          <p class="text-white"><span class="h4"><%= @artist_user.artist_name %></span> さんのTopics一覧</p>
        </div>
      <% else %>
      <!--アーティストは指定せず、全てのTopicsを表示させる場合-->
        <div>
          <h4 class="text-white">Topics一覧</h4>
        </div>
      <% end %>

      <!--アーティスト個別のTopics一覧を表示する際は、タグ一覧と検索フォームは表示させない-->
      <% unless params[:artist_id].present? %>
        <!--全てのタグを表示-->
        <div class="d-flex justify-content-center">
          <div class="col-md-8 tag-list-box mt-3 p-2 d-flex flex-wrap">
            <% @tag_lists.each do |tag_list| %>
              <!--タグ検索をできるようにリンクを設置-->
              <%= link_to admin_tag_topics_path(tag_list.id) do %>
                <div class="tags px-2 m-1">
                  <p class="text-white"><%= tag_list.name %><%="(#{tag_list.topics.count})" %></p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>

        <!--キーワード検索フォーム-->
        <div class="mt-3">
          <%= form_with url: search_admin_topics_path, method: :get do |f| %>
          <div class="d-flex">
            <%= f.text_field :keyword, value: @keyword, placeholder: 'Search', class: "col-4"%>
            <%= f.submit "検索する", class: "btn btn-success btn-green ml-2"%>
          </div>
          <% end %>
        </div>
      <% end %>

      <!--キーワード検索の際に、入力されたキーワードを表示させる-->
      <% if @keyword.present? %>
      <div class="mt-3">
        <div class="">
          <span class="text-white">"<%= @keyword %>"の検索結果</span>
        </div>
      </div>
      <% end %>

      <!--タグ検索の際に、何のタグで検索したかを表示させる-->
      <% if @search_display.present? %>
      <div class="d-flex mt-3">
        <div class="tags px-2">
          <span class="text-white"><%= @search_display %></span>
        </div>
        <span class="text-white ml-2">の関連Topics</span>
      </div>
      <% end %>

      <!--トピックス一覧の表示-->
      <% @topics.each do |topic| %>
        <div class="mini-topic-box">
          <div class="d-flex mt-3 px-3 pt-3">
            <!--プロフィール画像を表示-->
            <div class="ml-2">
              <%= image_tag topic.artist_user.profile_image, class: "mini-topic-profile-image" %>
            </div>
            <div class="ml-4 flex-fill">
              <!--アーティスト名を表示させ、アーティスト詳細画面へ遷移するリンクを設置-->
              <%= link_to admin_artist_user_path(topic.artist_user_id) do %>
                <span class="text-white mini-artist-name box px-2 py-1"><%= topic.artist_user.artist_name %></span>
                <% if topic.artist_user.is_deleted == true %>
                  <span class="mini-artist-name text-warning">（退会したユーザー）</span>
                <% end %>
              <% end %>

              <div class="topic-text">
                <!--トピックス本文を表示させ、トピックス詳細ページへのリンク-->
                <%= link_to admin_topic_path(topic) do %>
                  <p><%= simple_format topic.body, class: "text-white" %></p>
                <% end %>
              </div>
            </div>
          </div>

          <!--トピックスに紐づいているタグを表示-->
          <% if topic.tags.present? %>
          <div class="col-md-10 mx-auto d-flex flex-wrap">
            <% topic.tags.each do |tag| %>
              <!--取得したタグでタグ検索をできるようリンクを設置-->
              <%= link_to admin_tag_topics_path(tag.id) do %>
              <div class="tags px-2 m-1">
                <p class="text-white"><%= tag.name %></p>
              </div>
              <% end %>
            <% end %>
          </div>
          <% end %>

          <div class="col-md-10 mx-auto pb-1 d-flex justify-content-between">
            <!--トピックスの投稿日を表示-->
            <p class="text-white"><%= topic.created_at.strftime('%Y/%m/%d %H:%M') %></p>

            <div class="d-flex">
              <!--トピックスに画像が投稿されていた場合のアイコン表示-->
              <% if topic.topic_image.present? %>
              <p class="text-white mr-5"><i class="far fa-image"></i></p>
              <% end %>

              <!--トピックスにyoutubeのリンクが投稿されていた場合のアイコン表示-->
              <% if topic.youtube_url.present? %>
              <p class="text-white mr-5"><i class="fab fa-youtube"></i></p>
              <% end %>

              <!--いいね数の表示-->
              <p class="text-white ml-2"><i class="far fa-heart"></i> <%= topic.favorites.count %></p>

              <div class="ml-5">
                <!--トピックスに紐づいているコメントの数を表示-->
                <p class="text-white"><i class="far fa-comment-dots"></i> <%= topic.topic_comments.count %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!--ページネーションの表示-->
  	<div class="col-md-12 d-flex justify-content-center mt-5">
      <div>
        <%= paginate @topics %>
      </div>
    </div>

  </div>
</div>

app/views/admin/topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto mt-4">
      <div>
        <span class="h4 text-white">Topics</span>
      </div>

      <div class="row mt-3">
        <div class="topic-box">
          <div class="col-md-12">
            <div class="d-flex pt-4">
              <!--Artist会員のprofile画像を表示-->
              <%= image_tag @topic.artist_user.profile_image, class: "topic-profile-image ml-2" %>
              <!--Artist会員のアーティスト名を表示、クリックでArtist詳細画面に遷移させるため、リンクを設置-->
              <div class="d-flex align-items-center ml-5">
                <%= link_to admin_artist_user_path(@topic.artist_user_id) do %>
                  <h3 class="text-white"><%= @topic.artist_user.artist_name %></h3>
                <% end %>
                <% if @topic.artist_user.is_deleted == true %>
                  <p class="text-warning m-0 ml-3">（退会したユーザー）</p>
                <% end %>
              </div>
            </div>
          </div>

          <!--Topic投稿データにyoutubeリンクが登録されていた場合にiframeを表示-->
          <% if @topic.youtube_url.present? %>
            <div class="col-md-12 mt-3">
              <div class="topic-youtube-box">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @topic.youtube_url.last(11) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              </div>
            </div>
          <% end %>

          <!--Topic投稿データに画像が登録されていた場合に画像データを表示-->
          <% if @topic.topic_image.present? %>
            <div class="col-md-12 text-center mt-3">
              <%= image_tag @topic.topic_image, class: "topic-image" %>
            </div>
          <% end %>

          <!--Topicの本文-->
          <div class="col-md-12 text-center mt-3">
            <%= simple_format @topic.body, class: "text-white" %>
          </div>

          <!--トピックスに紐づいているタグを表示、クリックでタグ検索できるようボタンで表示-->
          <% if @topic.tags.present? %>
          <div class="col-md-10 mx-auto d-flex">
            <% @topic.tags.each do |tag| %>
              <%= link_to admin_tag_topics_path(tag.id) do %>
              <div class="tags px-2 m-1">
                <p class="text-white"><%= tag.name %></p>
              </div>
              <% end %>
            <% end %>
          </div>
          <% end %>

          <div class="col-md-10 mx-auto pl-5 border-bottom mb-3 d-flex justify-content-between">
            <!--投稿日の表示-->
            <p class="text-white"><%= @topic.created_at.strftime('%Y/%m/%d %H:%M') %></p>
            <div class="d-flex">
              <!--トピックスに画像が投稿されていた場合のアイコン表示-->
              <% if @topic.topic_image.present? %>
                <p class="text-white mr-5"><i class="far fa-image"></i></p>
              <% end %>

              <!--トピックスにyoutubeのリンクが投稿されていた場合のアイコン表示-->
              <% if @topic.youtube_url.present? %>
                <p class="text-white mr-5"><i class="fab fa-youtube"></i></p>
              <% end %>

              <!--いいね数の表示-->
              <p class="text-white ml-2"><i class="far fa-heart"></i> <%= @topic.favorites.count %></p>

              <!--Topicに紐づくコメントの数を表示-->
              <div class="ml-5">
                <p class="text-white"><i class="far fa-comment-dots"></i> <%= @topic.topic_comments.count %></p>
              </div>
            </div>
          </div>

          <!--削除ボタンを表示-->
          <div class="flex-fill text-right mr-4 pb-2">
            <%= link_to "削除", admin_topic_path(@topic), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-red btn-danger px-5" %>
          </div>

        </div>
      </div>

      <div class="row mt-5">
        <div class="col-md-12 text-white">
          <!--コメント数の表示-->
          <h5>Comments (<%= @topic_comments.count %>)</h5>
        </div>
      </div>

      <!--コメントの表示-->
      <div class="row">
        <div class="col-md-12 topic-comment-box">
          <% if @topic_comments.present? %>
            <% @topic_comments.each do |topic_comment| %>
              <div class="text-white border-bottom">
                <div class="d-flex pt-3 pl-3 pr-3">
                  <!--topic_commentに紐づいているidが一般会員の場合のコメント表示(public_user)-->
                  <% if topic_comment.public_user_id.present? %>
                    <div class="ml-2">
                      <!--プロフィール画像を表示-->
                      <%= image_tag topic_comment.public_user.get_profile_image, class: "comment-profile-image" %>
                    </div>
                    <div class="ml-5 flex-fill">
                      <!--ニックネームを表示させ、一般会員詳細画面へ遷移するリンクを設置-->
                      <%= link_to admin_public_user_path(topic_comment.public_user.id) do %>
                        <span class="text-white mini-artist-name box p-1"><%= topic_comment.public_user.nickname %></span>
                      <% end %>
                      <% if topic_comment.public_user.is_deleted == true %>
                        <span class="text-warning mini-artist-name">（退会したユーザー）</span>
                      <% end %>
                      <!--コメントの本文を表示-->
                      <p><%= simple_format topic_comment.comment %></p>

                      <div class="d-flex justify-content-end">
                        <!--コメント投稿日時を表示-->
                        <span class="mr-5"><%= topic_comment.created_at.strftime('%Y/%m/%d') %></span>
                        <!--削除ボタンを設置-->
                        <%= link_to "削除", admin_topic_topic_comment_path(topic_comment.topic, topic_comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger btn-red btn-sm px-3" %>
                      </div>
                    </div>

                  <!--topic_commentに紐づいているidがアーティスト会員の場合のコメント表示(artist_user)-->
                  <% elsif topic_comment.artist_user_id.present? %>
                    <div class="ml-2">
                      <!--プロフィール画像を表示-->
                      <%= image_tag topic_comment.artist_user.get_profile_image, class: "comment-profile-image" %>
                    </div>
                    <div class="ml-5 flex-fill">
                      <!--トピック投稿者本人の場合のコメント表示-->
                      <% if topic_comment.artist_user_id == @topic.artist_user_id %>
                        <!--アーティスト名を表示させ、Artist会員詳細画面へ遷移するリンクを設置-->
                        <%= link_to admin_artist_user_path(topic_comment.artist_user.id) do %>
                          <span class="text-white mini-artist-name box-2 p-1"><%= topic_comment.artist_user.artist_name %> <i class="fas fa-music"></i></span>
                        <% end %>
                        <span class="text-white-50 mini-artist-name">(投稿者)</span>

                      <!--トピックス投稿者本人ではない場合-->
                      <% else %>
                        <!--アーティスト名を表示させ、Artist会員詳細画面へ遷移するリンクを設置-->
                        <%= link_to admin_artist_user_path(topic_comment.artist_user.id) do %>
                          <span class="text-white mini-artist-name box p-1"><%= topic_comment.artist_user.artist_name %> <i class="fas fa-music"></i></span>
                        <% end %>
                      <% end %>
                      <% if topic_comment.artist_user.is_deleted == true %>
                        <span class="text-warning mini-artist-name">（退会したユーザー）</span>
                      <% end %>
                      <!--コメント本文の表示-->
                      <p class="mt-2"><%= simple_format topic_comment.comment %></p>

                      <div class="d-flex justify-content-end">
                        <!--コメント投稿日時を表示-->
                        <span class="mr-5"><%= topic_comment.created_at.strftime('%Y/%m/%d') %></span>
                        <!--削除ボタンを設置-->
                        <%= link_to "削除", admin_topic_topic_comment_path(topic_comment.topic, topic_comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger btn-red btn-sm px-3" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <!--コメントが投稿されていない場合の表示-->
          <% else %>
            <div class="mt-3 text-center">
              <span class="text-white">コメントは投稿されていません。</span>
            </div>
          <% end %>

          <!--ページネーションの表示-->
          <div class="col-md-12 d-flex justify-content-center mt-3">
            <div>
              <%= paginate @topic_comments %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>