config/routes.rb
Rails.application.routes.draw do

  # アーティスト会員用
  namespace :artist do
    resources :public_users, only:[:show] do
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
    end
    resources :artist_users, only:[:index] do
      collection do
        get 'my_page' => 'artist_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'my_page/my_topics' => 'artist_users#my_topics'
        get 'information/edit' => 'artist_users#edit'
        patch 'information' => 'artist_users#update'
        get 'unsubscribe' => 'artist_users#unsubscribe'
        patch 'hide' => 'artist_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
        get 'search' => 'artist_users#search'
      end

      member do
        get 'profile' => 'profiles#show'
        get 'profile/edit' => 'profiles#edit'
        patch 'profile' => 'profiles#update', as: 'profile_update'
      end
      resources :live_schedules, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :items, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :profile_topics, only:[:index]
      resources :rooms, only:[:index]
      # resource :relationships, only:[:create, :destroy]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
    end

    resources :genres, only:[:index, :create]
    resources :topics do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
        delete 'topic/:id' => 'topics#from_index_destroy', as: 'from_index_destroy'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
  end

  namespace :public do
    resources :public_users, only:[] do
      collection do
        get 'my_page' => 'public_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'information/edit' => 'public_users#edit'
        patch 'information' => 'public_users#update'
        get 'unsubscribe' => 'public_users#unsubscribe'
        patch 'hide' => 'public_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
      end
      get 'profile' => 'public_users#public_profile'
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
      resources :rooms, only:[:index]
    end
    resources :artist_users, only:[:index] do
      member do
        get 'profile' => 'profiles#show'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
      resources :live_schedules, only:[:index]
      resources :items, only:[:index]
      resources :profile_topics, only:[:index]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
    end
    resources :topics, only:[:index, :show] do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 管理者用
  namespace :admin do
    get '/' => 'homes#top'
    resources :public_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'public_users#guest_delete'
      end
      collection do
        get 'search' => 'public_users#search'
      end
    end
    resources :artist_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'artist_users#guest_delete'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
    end
    resources :genres, only:[:index, :edit, :create, :update, :destroy]
    resources :topics, only:[:index, :show, :destroy] do
      resources :topic_comments, only:[:destroy]
      collection do
        resources :tags, only:[:index, :destroy]
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員ゲストログイン用
  devise_scope :public_user do
    post 'public_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # Artist会員ゲストログイン用
  devise_scope :artist_user do
    post 'artist_users/guest_sign_in', to: 'artist/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # アーティスト会員用
  devise_for :artist_users,skip: [:passwords], controllers: {
    registrations: "artist/registrations",
    sessions: "artist/sessions"
  }

  # 一般会員用
  devise_for :public_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    # 全てのArtist会員を取得
    @artist_users = ArtistUser.all

    # Artist会員 ゲストユーザーを取得
    @guest_artist = ArtistUser.find_by(email: 'guest@example.com')

    # 退会しているArtist会員を取得
    @no_active_artist_users = ArtistUser.deleted

    # ジャンル設定をしていないArtist会員の取得
    @genre_nil_artsit_users = ArtistUser.where(genre_id: nil).all

    # 全ての一般会員を取得
    @public_users = PublicUser.all

    # 一般会員 ゲストユーザーを取得
    @guest_public = PublicUser.find_by(email: 'guest@example.com')

    # 退会している一般会員を取得
    @no_active_public_users = PublicUser.deleted

    # 全てのトピックスを取得
    @topics = Topic.includes(:tags)

    # 全てのタグを取得
    @tags = Tag.all

    # 関連トピックスが無いタグの取得
    true_topics_tags = []
    @topics.each do |topic|
      # 取得した全てのtopicsを展開し、タグが存在する際には、そのtag.idをtrue_topics_tagsに格納する
      if topic.tags.present?
        topic.tags.each do |tag|
          true_topics_tags << tag.id
        end
      end
    end
    # 上記で格納したtag.idは関連トピックスが存在するので、それ以外(関連トピックス無し)のTagを取得
    @no_topics_tags = Tag.where.not(id: true_topics_tags)

    # 全てのジャンルを取得
    @genres = Genre.all

    # 設定者が０のGenreを取得するための記述
    # 全Artsit会員のgenre_idを取得し、true_artist_genresに格納
    true_artist_genres = []
    @artist_users.each do |artist|
      true_artist_genres << artist.genre_id
    end
    # 上記で格納したgenre_idは設定者が存在するので、それ以外(設定者無し)のGenreを検索し取得
    @no_artist_genres = Genre.where.not(id: true_artist_genres)

  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container-fluid main-visual">
  <div class="row">
    <div class="col-md-7 top-menu text-white p-3">
      <div class="row">
        <!--Artist会員管理ボックス-->
        <div class="col-md-5 mx-auto mt-3 box p-3">
          <div class="text-center">
            <span class="text-white h5 border-bottom">Artist会員 管理</span>
          </div>

          <div class="row mt-4 text-center">
            <div class="col-md-7">
              <span class="text-white">登録アカウント数</span>
            </div>
            <div class="col-md-3">
              <span class="text-white"><%= @artist_users.count %></span>
            </div>
            <div class="col-md-7 mt-2">
              <span class="text-white">ゲストアカウント</span>
            </div>
            <div class="col-md-3 mt-2">
              <!--ゲストユーザーが存在するかどうか判断-->
              <% if @guest_artist.present? %>
                <!--ゲストユーザーの詳細画面へ遷移するリンクを設置-->
                <%= link_to admin_artist_user_path(@guest_artist) do %>
                  <span class="text-warning border-warning border-bottom">有</span>
                <% end %>
              <% else %>
                <span class="text-white">無</span>
              <% end %>
            </div>
            <div class="col-md-7 mt-2">
              <span class="text-warning">退会済みアカウント</span>
            </div>
            <div class="col-md-3 mt-2">
              <!--退会済みアカウントのみの一覧をArtist会員一覧画面で表示させるためにform_tagでリンクを設置-->
              <%= form_tag admin_artist_users_path do %>
                <%= link_to admin_artist_users_path(no_active: 0), class: "border-warning border-bottom" do %>
                  <span class="text-warning"><%= @no_active_artist_users.count %></span>
                <% end %>
              <% end %>
            </div>

            <div class="col-md-7 mt-2">
              <span class="text-warning">ジャンル未設定者</span>
            </div>
            <div class="col-md-3 mt-2">
              <!--ジャンル未設定アカウント一覧をArtist会員一覧画面で表示させるためにform_tagでリンクを設置-->
              <%= form_tag admin_artist_users_path do %>
                <%= link_to admin_artist_users_path(genre_nil: 0), class: "border-warning border-bottom" do %>
                  <span class="text-warning"><%= @genre_nil_artsit_users.count %></span>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="text-center mt-4">
            <%= link_to "管理画面", admin_artist_users_path, class: "btn btn-follow btn-success" %>
          </div>
        </div>

        <!--一般会員管理ボックス-->
        <div class="col-md-5 mx-auto mt-3 box p-3">
          <div class="text-center">
            <span class="text-white h5 border-bottom">一般会員 管理</span>
          </div>
          <div class="row mt-4 text-center">
            <div class="col-md-7">
              <span class="text-white">登録アカウント数</span>
            </div>
            <div class="col-md-3">
              <span class="text-white"><%= @public_users.count %></span>
            </div>
            <div class="col-md-7 mt-2">
              <span class="text-white">ゲストアカウント</span>
            </div>
            <div class="col-md-3 mt-2">
              <!--ゲストユーザーが存在するか判断-->
              <% if @guest_public.present? %>
                <!--ゲストユーザーの詳細画面へ遷移するリンクを設置-->
                <%= link_to admin_public_user_path(@guest_public) do %>
                  <span class="text-warning border-warning border-bottom">有</span>
                <% end %>
              <% else %>
                <span class="text-white">無</span>
              <% end %>
            </div>
            <div class="col-md-7 mt-2">
              <span class="text-warning">退会済みアカウント</span>
            </div>
            <div class="col-md-3 mt-2">
              <!--退会済みアカウントのみの一覧を一般会員一覧画面で表示させるためにform_tagでリンクを設置-->
              <%= form_tag admin_public_users_path do %>
                <%= link_to admin_public_users_path(no_active: 0), class: "border-warning border-bottom" do %>
                  <span class="text-warning"><%= @no_active_public_users.count %></span>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="text-center mt-5">
            <%= link_to "管理画面", admin_public_users_path, class: "btn btn-follow btn-success" %>
          </div>
        </div>

        <!--Topics・タグ管理ボックス-->
        <div class="col-md-5 mx-auto mt-5 mb-3 box p-3">
          <div class="text-center">
            <span class="text-white h5 border-bottom">Topics・Tag 管理</span>
          </div>
          <div class="row mt-4 text-center">
            <div class="col-md-7">
              <span class="text-white">Topics 投稿数</span>
            </div>
            <div class="col-md-3">
              <span class="text-white"><%= @topics.count %></span>
            </div>
            <div class="col-md-7 mt-2">
              <span class="text-white">タグ数</span>
            </div>
            <div class="col-md-3 mt-2">
              <span class="text-white"><%= @tags.count %></span>
            </div>
            <div class="col-md-7 mt-2">
              <span class="text-warning">関連Topics無しのタグ数</span>
            </div>
            <div class="col-md-3 mt-2">
              <!--関連Topicsの存在しないタグ一覧をタグ一覧画面で表示させるためにform_tagでリンクを設置-->
              <%= form_tag admin_tags_path do %>
                <%= link_to admin_tags_path(topics_nil: 0), class: "border-warning border-bottom" do %>
                  <span class="text-warning"><%= @no_topics_tags.count %></span>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="text-center mt-4">
            <%= link_to "Topics管理画面", admin_topics_path, class: "btn btn-follow btn-success mr-3" %>
            <%= link_to "Tags管理画面", admin_tags_path, class: "btn btn-follow btn-success" %>
          </div>
        </div>

        <!--ジャンル管理ボックス-->
        <div class="col-md-5 mx-auto mt-5 mb-3 box p-3">
          <div class="text-center">
            <span class="text-white h5 border-bottom">Genres 管理</span>
          </div>
          <div class="row mt-4 text-center">
            <div class="col-md-7">
              <span class="text-white">Genre数</span>
            </div>
            <div class="col-md-3">
              <span class="text-white"><%= @genres.count %></span>
            </div>
            <div class="col-md-7 mt-2">
              <span class="text-warning">登録Artistが 0 のGenre</span>
            </div>
            <div class="col-md-3 mt-2">
              <!--登録Artistが存在しないジャンル一覧をジャンル一覧画面で表示させるためにform_tagでリンクを設置-->
              <%= form_tag admin_genres_path do %>
                <%= link_to admin_genres_path(genre_artist_nil: 0), class: "border-warning border-bottom" do %>
                  <span class="text-warning"><%= @no_artist_genres.count %></span>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="text-center mt-4">
            <%= link_to "管理画面", admin_genres_path, class: "btn btn-follow btn-success" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>