config/routes.rb
Rails.application.routes.draw do

  # アーティスト会員用
  namespace :artist do
    resources :public_users, only:[:show] do
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
    end
    resources :artist_users, only:[:index] do
      collection do
        get 'my_page' => 'artist_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'my_page/my_topics' => 'artist_users#my_topics'
        get 'information/edit' => 'artist_users#edit'
        patch 'information' => 'artist_users#update'
        get 'unsubscribe' => 'artist_users#unsubscribe'
        patch 'hide' => 'artist_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
        get 'search' => 'artist_users#search'
      end

      member do
        get 'profile' => 'profiles#show'
        get 'profile/edit' => 'profiles#edit'
        patch 'profile' => 'profiles#update', as: 'profile_update'
      end
      resources :live_schedules, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :items, only:[:new, :create, :index, :edit, :update, :destroy]
      resources :profile_topics, only:[:index]
      resources :rooms, only:[:index]
      # resource :relationships, only:[:create, :destroy]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
    end

    resources :genres, only:[:index, :create]
    resources :topics do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
        delete 'topic/:id' => 'topics#from_index_destroy', as: 'from_index_destroy'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員用
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
  end

  namespace :public do
    resources :public_users, only:[] do
      collection do
        get 'my_page' => 'public_users#show'
        get 'my_page/favorite_topics' => 'favorites#index'
        get 'information/edit' => 'public_users#edit'
        patch 'information' => 'public_users#update'
        get 'unsubscribe' => 'public_users#unsubscribe'
        patch 'hide' => 'public_users#hide'
        post 'rooms' => 'rooms#create', as: 'rooms_create'
        get 'rooms/:id' => 'rooms#show', as: 'rooms'
        post 'messages' => 'messages#create'
      end
      get 'profile' => 'public_users#public_profile'
      post 'relationships' => 'relationships#public_follow'
      delete 'relationships' => 'relationships#public_unfollow'
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # resources :favorites, only:[:index]
      resources :rooms, only:[:index]
    end
    resources :artist_users, only:[:index] do
      member do
        get 'profile' => 'profiles#show'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
      resources :live_schedules, only:[:index]
      resources :items, only:[:index]
      resources :profile_topics, only:[:index]
      post 'relationships' => 'relationships#artist_follow'
      delete 'relationships' => 'relationships#artist_unfollow'
    end
    resources :topics, only:[:index, :show] do
      resources :topic_comments, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
      collection do
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 管理者用
  namespace :admin do
    get '/' => 'homes#top'
    resources :public_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'public_users#guest_delete'
      end
      collection do
        get 'search' => 'public_users#search'
      end
    end
    resources :artist_users, only:[:index, :show, :edit, :update] do
      member do
        delete 'delete' => 'artist_users#guest_delete'
      end
      collection do
        get 'search' => 'artist_users#search'
      end
    end
    resources :genres, only:[:index, :edit, :create, :update, :destroy]
    resources :topics, only:[:index, :show, :destroy] do
      resources :topic_comments, only:[:destroy]
      collection do
        resources :tags, only:[:index, :destroy]
        get 'search' => 'topics#search'
      end
    end
    resources :tags, only:[] do
      get 'topics', to: 'topics#tag_search'
    end
  end

  # 一般会員ゲストログイン用
  devise_scope :public_user do
    post 'public_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # Artist会員ゲストログイン用
  devise_scope :artist_user do
    post 'artist_users/guest_sign_in', to: 'artist/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # アーティスト会員用
  devise_for :artist_users,skip: [:passwords], controllers: {
    registrations: "artist/registrations",
    sessions: "artist/sessions"
  }

  # 一般会員用
  devise_for :public_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/artist/artist_users_controller.rb
class Artist::ArtistUsersController < ApplicationController
  before_action :authenticate_artist_user!
  # Artist一覧画面
  def index
    @genres = Genre.all
    @artist_user = current_artist_user
    @search_params = artist_user_search_params

    # サイドバーのジャンル検索ボタンを押された時の処理
    if params[:name].present?
      # 指定されたジャンルに紐づいている、退会していないArtistUserを取得
      @artist_users = Genre.find(params[:name]).artist_users.active.order(created_at: :desc).page(params[:page]).per(9)
    else
      # 退会していないArtistUserを取得
      @artist_users = ArtistUser.active.order(created_at: :desc).page(params[:page]).per(9)
    end
  end

  # Artist検索アクション
  def search
    @artist_user = current_artist_user
    @genres = Genre.all
    @search_params = artist_user_search_params
    # 最新順でArtistUserを表示させる場合
    if params[:display_select] == "1"
      @artist_users = ArtistUser.active.search(@search_params).includes(:genre).order(created_at: :desc).page(params[:page]).per(9)
    # 登録日順でArtistUserを表示させる場合
    elsif params[:display_select] == "2"
      @artist_users = ArtistUser.active.search(@search_params).includes(:genre).page(params[:page]).per(9)
    # フォロワーが多い順でArtistUserを表示させる場合
    elsif params[:display_select] == "3"
      @artist_users = Kaminari.paginate_array(ArtistUser.active.search(@search_params).includes(:genre).sort {|a, b| b.active_followers.count.to_i <=> a.active_followers.count.to_i}).page(params[:page]).per(9)
    # フォロワーが少ない順でArtistUserを表示させる場合
    elsif params[:display_select] == "4"
      @artist_users = Kaminari.paginate_array(ArtistUser.active.search(@search_params).includes(:genre).sort {|a, b| a.active_followers.count.to_i <=> b.active_followers.count.to_i}).page(params[:page]).per(9)
    end
    render "index"
  end

  # My page
  def show
    @artist_user = current_artist_user
    # TimeLineを表示するため、自身のtopicsとfollowしている退会していないユーザーのtopicsを取得
    @topics = Topic.active_topics.where(artist_user_id: [current_artist_user.id, *current_artist_user.artist_following_ids]).order(created_at: :desc).page(params[:page]).per(10)
  end

  # My pageで自身が投稿したtopic一覧を表示するためのアクション
  def my_topics
    @artist_user = current_artist_user
    @topics = @artist_user.topics.order(created_at: :desc).page(params[:page]).per(10)
  end

  # 登録情報編集画面
  def edit
    @artist_user = current_artist_user
  end

  # 登録情報更新
  def update
    @artist_user = current_artist_user
    # ログイン中のユーザーがゲストユーザーの場合はアーティスト名、メールアドレス以外を編集可能にする。
    if @artist_user.email == 'guest@example.com'
      flash[:notice] = "ゲストユーザーのため、アーティスト名、メールアドレス以外を更新しました。"
      @artist_user.update(params.require(:artist_user).permit(:profile_image, :rep_name, :rep_name_kana, :activity_location, :genre_id))
      redirect_to my_page_artist_artist_users_path
    else
      flash[:notice] = "登録情報を更新しました。"
      @artist_user.update(artist_user_params)
      redirect_to my_page_artist_artist_users_path
    end
  end

  # 退会確認画面
  def unsubscribe
    @artist_user = current_artist_user
  end

  # 退会処理(論理削除)
  def hide
    @artist_user = current_artist_user
    @artist_user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private
  # ストロングパラメータ
  def artist_user_params
    params.require(:artist_user).permit(:profile_image, :artist_name, :rep_name, :rep_name_kana, :activity_location, :email, :genre_id)
  end

  def artist_user_search_params
    params.fetch(:search, {}).permit(:artist_name, :genre_id, :activity_location)
  end
end

app/controllers/artist/artists_controller.rb
class Artist::ArtistsController < ApplicationController
  def index
    @artist_users = ArtistUser.all
  end

  def show
    @artist_user = ArtistUser.find(params[:id])
  end

  def edit
    @artist_user = ArtistUser.find(params[:id])
  end

  def update
    @artist_user = ArtistUser.find(params[:id])
    @artist_user.update(profile_params)
    redirect_to profile_artist_path(@artist_user)
  end

  private

  def profile_params
    params.require(:artist_user).permit(:header_image, :youtube_url)
  end
end

app/controllers/artist/confirmations_controller.rb
# frozen_string_literal: true

class Artist::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/artist/favorites_controller.rb
class Artist::FavoritesController < ApplicationController
  before_action :set_variables, only:[:create, :destroy]
  # いいねしたトピックス一覧
  def index
    @artist_user = current_artist_user
    favorites = Favorite.where(artist_user_id: @artist_user.id).pluck(:topic_id)
    @topics = Topic.active_topics.where(id: favorites).order(created_at: :desc).page(params[:page]).per(10)
  end

  # いいねアクション
  def create
    topic = Topic.find(params[:topic_id])
    favorite = current_artist_user.favorites.new(topic_id: topic.id)
    favorite.save
  end

  # いいねを取り消すアクション
  def destroy
    topic = Topic.find(params[:topic_id])
    favorite = current_artist_user.favorites.find_by(topic_id: topic.id)
    favorite.destroy
  end

  private

  def set_variables
    @topic = Topic.find(params[:topic_id])
    @id_name = "#topic-favorite-#{@topic.id}"
  end
end

app/controllers/artist/genres_controller.rb
class Artist::GenresController < ApplicationController
  before_action :authenticate_artist_user!
  # ジャンル一覧・新規作成画面
  def index
    @artist_user = current_artist_user
    @genre = Genre.new
    @genres = Genre.all
  end

  # ジャンル新規作成
  def create
    @genre = Genre.new(genre_params)
    # ジャンルを新規作成する際に、アーティストのジャンルを新規作成したジャンルに変更させる。
    if @genre.save
      current_artist_user.genre_id = @genre.id
      current_artist_user.save
      flash[:notice] = "ジャンルを新規作成し、登録しました。"
      redirect_to my_page_artist_artist_users_path
    else
      @artist_user = current_artist_user
      @genres = Genre.all
      render :index
    end
  end

  private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/artist/items_controller.rb
class Artist::ItemsController < ApplicationController
  before_action :authenticate_artist_user!
  # Item新規登録画面
  def new
    @item = Item.new
  end

  # Item新規登録アクション
  def create
    @item = current_artist_user.items.new(item_params)
    if @item.save
      redirect_to artist_artist_user_items_path
    else
      render :new
    end
  end

  # Item一覧画面
  def index
    @artist_user = ArtistUser.find(params[:artist_user_id])
    @items = @artist_user.items

    # DM機能のための記述
    # Roomを作成した際に、現在ログインしているユーザーと、対象ユーザーの両方をjoinsテーブルに記録するためwhereで取得
    @current_ArtistUser_join = Join.where(artist_user_id: current_artist_user.id)
    @ArtistUser_join = Join.where(artist_user_id: @artist_user.id)

    # 対象ユーザーが現在ログインしているユーザーではない場合
    unless @artist_user.id == current_artist_user.id
      # 現在ログインしているユーザーと対象ユーザーのメッセージRoomが既に作成されているかを判断
      @current_ArtistUser_join.each do |current_artist|
        @ArtistUser_join.each do |other_artist|
          if current_artist.room_id == other_artist.room_id then
            @isRoom = true
            @roomId = current_artist.room_id
          end
        end
      end
      # 上記でメッセージRoomが存在しなかった場合、新しくインスタンスを作成するための記述
      if @isRoom
      else
        @room = Room.new
        @join = Join.new
      end
    end
  end

  # Item編集画面
  def edit
    @item = Item.find(params[:id])

    # 他者のItem編集画面へ遷移させない
    if @item.artist_user != current_artist_user
      redirect_to artist_artist_user_items_path(current_artist_user)
    end
  end

  # Item情報更新
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to artist_artist_user_items_path
  end

  # Item情報削除
  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to artist_artist_user_items_path
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:artist_user_id, :name, :introduction, :item_image, :price)
  end
end

app/controllers/artist/live_schedules_controller.rb
class Artist::LiveSchedulesController < ApplicationController
  before_action :authenticate_artist_user!
  # Live Schedule一覧画面
  def index
    @artist_user = ArtistUser.find(params[:artist_user_id])
    @live_schedules = @artist_user.live_schedules

    # DM機能のための記述
    # Roomを作成した際に、現在ログインしているユーザーと、対象ユーザーの両方をjoinsテーブルに記録するためwhereで取得
    @current_ArtistUser_join = Join.where(artist_user_id: current_artist_user.id)
    @ArtistUser_join = Join.where(artist_user_id: @artist_user.id)

    # 対象ユーザーが現在ログインしているユーザーではない場合
    unless @artist_user.id == current_artist_user.id
      # 現在ログインしているユーザーと対象ユーザーのメッセージRoomが既に作成されているかを判断
      @current_ArtistUser_join.each do |current_artist|
        @ArtistUser_join.each do |other_artist|
          if current_artist.room_id == other_artist.room_id then
            @isRoom = true
            @roomId = current_artist.room_id
          end
        end
      end
      # 上記でメッセージRoomが存在しなかった場合、新しくインスタンスを作成するための記述
      if @isRoom
      else
        @room = Room.new
        @join = Join.new
      end
    end
  end

  # Live Schedule新規登録画面
  def new
    @live_schedule = LiveSchedule.new
  end

  # Live Schedule新規登録
  def create
    @live_schedule = current_artist_user.live_schedules.new(live_schedule_params)
    if @live_schedule.save
      redirect_to artist_artist_user_live_schedules_path
    else
      render :new
    end
  end

  # Live Schedule情報編集
  def edit
    @live_schedule = LiveSchedule.find(params[:id])

    # 他者のLiveSchedule編集画面へ遷移させない
    if @live_schedule.artist_user != current_artist_user
      redirect_to artist_artist_user_live_schedules_path(current_artist_user)
    end
  end

  # Live Schedule情報更新
  def update
    @live_schedule = LiveSchedule.find(params[:id])
    if @live_schedule.update(live_schedule_params)
      redirect_to artist_artist_user_live_schedules_path
    else
      render :edit
    end
  end

  # Live Schedule情報削除
  def destroy
    live_schedule = LiveSchedule.find(params[:id])
    live_schedule.destroy
    redirect_to artist_artist_user_live_schedules_path
  end

  private
  # ストロングパラメータ
  def live_schedule_params
    params.require(:live_schedule).permit(:artist_user_id, :name, :schedule_date, :price, :location)
  end
end

app/controllers/artist/messages_controller.rb
class Artist::MessagesController < ApplicationController
  before_action :authenticate_artist_user!
  # ダイレクトメッセージ送信
  def create
    if Join.where(artist_user_id: current_artist_user.id, room_id: params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:artist_user_id, :content, :room_id).merge(artist_user_id: current_artist_user.id))
    else
      flash[:alert] = "送信に失敗しました。"
    end
    redirect_to request.referer
  end
end

app/controllers/artist/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Artist::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/views/artist/relationships/_artist_dm_button.html.erb
<!--取得したArtist会員のIDが、ログイン中のArtist会員のIDと一致しない場合-->
<% if artist_user_signed_in? && artist_user.id != current_artist_user.id %>
  <!--対象をフォローしているかどうかを判断-->
  <% if current_artist_user.artist_following?(artist_user) %>
    <!--取得したArtistとのDMのやり取りをするRoomが存在する場合は、そのページへ遷移するボタンを設置-->
    <% if isRoom == true %>
      <%= link_to "Messageを送る", rooms_artist_artist_users_path(roomId), class: "btn btn-green btn-primary mt-3" %>
    <% else %>
      <!--Roomが存在しない場合は、新しくRoomを作成する-->
      <%= form_with model: room, url: rooms_create_artist_artist_users_path do |f| %>
        <%= fields_for join do |j| %>
          <%= j.hidden_field :artist_user_id, value: artist_user.id %>
        <% end %>
        <%= f.submit "Messageを送る", class: "btn btn-primary btn-green mt-3" %>
      <% end %>
    <% end %>
  <% end %>
<!--ログインしているユーザーが一般会員の場合の表示-->
<% elsif public_user_signed_in? %>
  <!--対象をフォローしているかどうかを判断-->
  <% if current_public_user.artist_following?(artist_user) %>
    <!--取得したArtistとのDMのやり取りをするRoomが存在する場合は、そのページへ遷移するボタンを設置-->
    <% if isRoom == true %>
      <%= link_to "Messageを送る", rooms_public_public_users_path(roomId), class: "btn btn-green btn-primary mt-3" %>
    <% else %>
      <!--Roomが存在しない場合は、新しくRoomを作成する-->
      <%= form_with model: room, url: rooms_create_public_public_users_path do |f| %>
        <%= fields_for Join.new do |j| %>
          <%= j.hidden_field :artist_user_id, value: artist_user.id %>
        <% end %>
        <%= f.submit "Messageを送る", class: "btn btn-green btn-primary mt-3" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/artist/relationships/_artist_follow_button.html.erb
<%= link_to "+ Follow", artist_artist_user_relationships_path(artist.id), method: :post, remote: true, class: "btn btn-follow btn-success btn-lg" %>

app/views/artist/relationships/_artist_unfollow_button.html.erb
<%= link_to "- Unfollow", artist_artist_user_relationships_path(artist.id), method: :delete, remote: true, class: "btn btn-red btn-danger btn-lg" %>

app/views/artist/relationships/_public_dm_button.html.erb
<!--対処をフォローしているかどうかを判断-->
<% if current_artist_user.public_following?(public_user) %>
  <!--対象とのDMを送り合うRoomが存在する場合は、そのページへ遷移するボタンを設置-->
  <% if isRoom == true %>
    <%= link_to "Messageを送る", rooms_artist_artist_users_path(roomId), class: "btn btn-green btn-primary" %>
  <% else %>
    <!--Roomが存在しない場合は新しく作成する-->
    <%= form_with model: room, url: rooms_create_artist_artist_users_path do |f| %>
      <%= fields_for Join.new do |j| %>
        <%= j.hidden_field :public_user_id, value: public_user.id %>
      <% end %>
      <%= f.submit "Messageを送る", class: "btn btn-green btn-primary" %>
    <% end %>
  <% end %>
<% end %>

app/views/artist/relationships/_public_follow_button.html.erb
<%= link_to "+ Follow", artist_public_user_relationships_path(public_user.id), method: :post, remote: true, class: "btn btn-success btn-follow btn-lg" %>

app/views/artist/relationships/_public_unfollow_button.html.erb
<%= link_to "- Unfollow", artist_public_user_relationships_path(public_user.id), method: :delete, remote: true, class: "btn btn-danger btn-red btn-lg" %>

app/views/artist/relationships/followers.html.erb
<div class="container">
  <div class="row mt-3">
    <!--マイページサイドバーの表示-->
    <div class="col-lg-3 d-flex">
      <%= render 'artist/artist_users/my_page', artist_user: @artist_user %>
    </div>

    <div class="col-lg-9">
      <div>
        <h3 class="text-white">Follower</h3>
      </div>

      <!--フォロワーが存在するか判断-->
      <% if @followers.present? %>
      <!--フォロワー一覧の表示-->
      <div class="row">
        <div class="col-md-12">
          <div class="row">
          <% @followers.each do |follower| %>
            <!--フォロワーのユーザーがArtist会員の場合の表示-->
            <% if follower.artist_follower_id.present? %>

              <div class="col-md-3 m-3 mini-profile-box">
                <div class="row">
                  <!--ヘッダー画像-->
                  <div class="col-md-12 mini-profile-header-box">
                    <%= image_tag follower.artist_follower.get_header_image, class: "mini-profile-header" %>
                  </div>
                  <!--プロフィール画像-->
                  <div class="col-md-12 text-center">
                    <div class=""><%= image_tag follower.artist_follower.get_profile_image, class: "mini-profile-box-image rounded-circle"; %></div>
                  </div>
                  <div class="mini-profile-detail col-md-12">
                    <!--Artistプロフィールページへ遷移するリンクをArtist名に設置-->
                    <div class="col-md-12 text-center">
                      <%= link_to profile_artist_artist_user_path(follower.artist_follower.id) , class: "text-white" do %>
                        <%= follower.artist_follower.artist_name %>
                      <% end %>
                    </div>
                    <div class="col-md-12 text-center">
                      <!--ジャンル登録がされているか判断-->
                      <% if follower.artist_follower.genre.present? %>
                        <span class="text-white">Genre: <%= follower.artist_follower.genre.name %></span><br>
                      <% else %>
                        <span class="text-white">Genre: 未設定</span><br>
                      <% end %>
                      <!--拠点エリアの表示-->
                      <span class="text-white"><%= follower.artist_follower.activity_location_i18n %></span>
                      <!--フォロワーの表示-->
                      <div class="follow-detail-display" id="follower-count-a-<%= follower.artist_follower.id %>">
                        <p>Follower：<%= follower.artist_follower.artist_reverse_of_relationships.follower_count %></p>
                      </div>
                    </div>
                    <!--紹介文の表示-->
                    <div class="introduction-box">
                      <div class="col-md-12 text-center text-white introduction-box-detail">
                        <!--紹介文が存在するか判断-->
                        <% if follower.artist_follower.introduction.present? %>
                          <p><%= simple_format follower.artist_follower.introduction %></p>
                        <% else %>
                          <p class="m-3">自己紹介文は登録されてません.</p>
                        <% end %>
                      </div>
                    </div>
                    <!--フォローボタンの表示-->
                    <div class="col-md-12 text-center mt-3" id="follow-ajax-a-<%= follower.artist_follower.id %>">
                      <!--フォローをしているかの判断-->
                      <% if current_artist_user.artist_following?(follower.artist_follower) %>
                        <%= render 'artist/relationships/artist_unfollow_button', artist: follower.artist_follower %>
                      <% else %>
                        <%= render 'artist/relationships/artist_follow_button', artist: follower.artist_follower %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>

            <!--フォロワーのユーザーが一般会員の場合の表示-->
            <% elsif follower.public_follower_id.present? %>
              <div class="col-md-3 m-3 mini-profile-box">
                <div class="row">
                  <div class="col-md-12 mini-profile-header">

                  </div>
                  <!--プロフィール画像-->
                  <div class="col-md-12 text-center">
                    <div class=""><%= image_tag follower.public_follower.get_profile_image, class: "mini-profile-box-image rounded-circle"; %></div>
                  </div>
                  <div class="mini-profile-detail col-md-12">
                    <!--一般会員詳細画面へ遷移するリンクをニックネームに設置-->
                    <div class="col-md-12 text-center">
                      <%= link_to artist_public_user_path(follower.public_follower.id) , class: "text-white" do %>
                        <%= follower.public_follower.nickname %>
                      <% end %>
                    </div>
                    <!--フォロワーの表示-->
                    <div class="follow-detail-display text-center" id="follower-count-p-<%= follower.public_follower.id %>">
                      <p>Follower：<%= follower.public_follower.public_reverse_of_relationships.follower_count %></p>
                    </div>
                    <div class="col-md-12 text-center">
                      <span class="text-white"></span></span>
                    </div>
                    <!--自己紹介文の表示-->
                    <div class="introduction-box-2">
                      <div class="col-md-12 text-center text-white introduction-box-detail">
                        <!--自己紹介文が存在するか判断-->
                        <% if follower.public_follower.introduction.present? %>
                          <p><%= simple_format follower.public_follower.introduction %></p>
                        <% else %>
                          <p class="m-3">自己紹介文は登録されてません.</p>
                        <% end %>
                      </div>
                    </div>
                    <!--フォローボタンの表示-->
                    <div class="col-md-12 text-center mt-3" id="follow-ajax-p-<%= follower.public_follower.id %>">
                      <!--フォローをしているか判断-->
                      <% if current_artist_user.public_following?(follower.public_follower) %>
                        <%= render 'artist/relationships/public_unfollow_button', public_user: follower.public_follower %>
                      <% else %>
                        <%= render 'artist/relationships/public_follow_button', public_user: follower.public_follower %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
          </div>
        </div>

        <!--ページネーションの表示-->
        <div class="col-md-10 d-flex justify-content-center mt-5">
          <div>
            <%= paginate @followers %>
          </div>
        </div>
      </div>

      <!--フォロワーが存在しない場合-->
      <% else %>
        <p class="text-white mt-3">あなたをフォローしているユーザーはいません。</p>
      <% end %>
    </div>
  </div>
</div>